# Generated by Django 4.2 on 2023-04-30 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madicalinfo',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='madicalinfo',
            name='blood_groop',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='madicalinfo',
            name='dept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employ_app.department'),
        ),
        migrations.AddField(
            model_name='madicalinfo',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
