# Generated by Django 4.2 on 2023-04-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0002_madicalinfo_age_madicalinfo_blood_groop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='madicalinfo',
            name='medical_problem',
            field=models.CharField(default='enter your problem!!', max_length=30),
        ),
    ]
