# Generated by Django 4.2 on 2023-04-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0003_madicalinfo_medical_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madicalinfo',
            name='medical_problem',
            field=models.TextField(default='enter your problem!!', max_length=3000),
        ),
    ]
