# Generated by Django 4.2 on 2023-05-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0004_alter_madicalinfo_medical_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madicalinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='madicalinfo',
            name='last_name',
        ),
    ]
