# Generated by Django 4.2 on 2023-05-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0005_remove_madicalinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='medical',
            field=models.TextField(default='enter your problem!!', max_length=3000),
        ),
        migrations.DeleteModel(
            name='MadicalInfo',
        ),
    ]
