# Generated by Django 4.2 on 2023-05-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0006_alter_employee_medical_delete_madicalinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='medical',
            new_name='medical_problem',
        ),
    ]
