# Generated by Django 4.2 on 2023-05-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0007_rename_medical_employee_medical_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='medical_problem',
            field=models.TextField(max_length=3000),
        ),
    ]
