# Generated by Django 4.2 on 2023-05-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0008_alter_employee_medical_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
