# Generated by Django 4.2 on 2023-05-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0009_remove_employee_dept_remove_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='employ_app.role'),
        ),
    ]
